version: '3.5'
services:

  redis:
    image: redis:7.0.5
    restart: always
    ports:
      - '6379:6379'
    command: /usr/local/bin/redis-server /config/redis.conf
    volumes: 
      - ./local/redis.conf:/config/redis.conf
      - ./local/.persist/redis/:/data

  postgresql:
    image: bitnami/postgresql:13-debian-12
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_USERNAME: henry_chou
      POSTGRESQL_PASSWORD: admin1337tw
      POSTGRESQL_DATABASE: my-demo-db
    volumes:
      - ./local/.persist/redis/postgresql:/bitnami/postgresql
      # - 'postgresql_data:/bitnami/postgresql'

  mongo:
    image: mongo:6.0.3
    restart: always
    ports:
      - '27017:27017'
    command: mongod --dbpath /data/db --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: henry_chou
      MONGO_INITDB_ROOT_PASSWORD: admin1337tw
    volumes:
      - ./local/.persist/mongo/data:/data/db

# volumes:
#   postgresql_data:
#     driver: local